export enum SETTINGS_IPC_CHANNELS {
  GET = 'SETTINGS_IPC_CHANNELS.GET',
  UPDATE = 'SETTINGS_IPC_CHANNELS.UPDATE'
}

export enum SOURCES_IPC_CHANNELS {
  GET_ALL = 'SOURCES_IPC_CHANNELS.GET_ALL',
  CREATE = 'SOURCES_IPC_CHANNELS.CREATE',
  UPDATE = 'SOURCES_IPC_CHANNELS.UPDATE',
  REMOVE = 'SOURCES_IPC_CHANNELS.REMOVE'
}

export enum SHARED_IPC_CHANNELS {
  SELECT_FOLDER = 'SHARED_IPC_CHANNELS.SELECT_FOLDER'
}
