export { BaseEntity } from './entities/BaseEntity'
export { setupSharedIpcHandlers } from './ipc/setupSharedIpcHandlers'
export { addIpcListener, addIpcListenerWithPayload } from './ipc/utils/addIpcListener'
export type { AppPaths } from './utils/appPaths'
export { appPaths } from './utils/appPaths'
export { normalizeError } from './utils/normalize-error/normalizeError'
