export type ZipServiceErrorCode =
  | 'ZIP_LIST_CONTENTS_ABORTED'
  | 'ZIP_LIST_CONTENTS_FAILED'
  | 'ZIP_EXTRACT_FAILED'
  | 'ZIP_ARCHIVE_FAILED'
  | 'ZIP_COLLECT_ENTRIES_FAILED'
  | 'ZIP_TO_ZIP_ENTRY_NAME_FAILED'
  | 'ZIP_PATH_JOIN_REL_FAILED'
