export const TASK_TYPE = {
  MULTIPLY: 'TASK_TYPE__MULTIPLY',
  SCAN_SOURCE: 'TASK_TYPE__SCAN_SOURCE',
  EXTRACT_ARCHIVE: 'TASK_TYPE__EXTRACT_ARCHIVE',
  CREATE_ACRHIVE: 'TASK_TYPE__CREATE_ACRHIVE',
  NORMALIZE_FILES: 'TASK_TYPE__NORMALIZE_FILES'
} as const

export const TASK_STATUS = {
  PENDING: 'TASK_STATUS__PENDING',
  RUNNIGN: 'TASK_STATUS__RUNNIGN',
  COMPLETED: 'TASK_STATUS__COMPLETED',
  FAILED: 'TASK_STATUS__FAILED',
  CANCELLED: 'TASK_STATUS__CANCELLED'
} as const

export const TASKS_QUEUE_STATUS = {
  PENDING: 'TASKS_QUEUE_STATUS__PENDING',
  RUNNIGN: 'TASKS_QUEUE_STATUS__RUNNIGN',
  COMPLETED: 'TASKS_QUEUE_STATUS__COMPLETED',
  FAILED: 'TASKS_QUEUE_STATUS__FAILED',
  CANCELLED: 'TASKS_QUEUE_STATUS__CANCELLED'
} as const
