export const TASK_TYPE = {
  MULTIPLY: 'MULTIPLY',
  SCAN_SOURCE: 'SCAN_SOURCE',
  EXTRACT_ARCHIVE: 'EXTRACT_ARCHIVE',
  CREATE_ACRHIVE: 'CREATE_ACRHIVE',
  NORMALIZE_FILES: 'NORMALIZE_FILES'
} as const
